### ISSUE TITLE
ウルトラマン拉致 ウルトラマンが拉致されて 腹筋ボコボコにパンチ食らって 胸のランプが点滅すると あと3分で力尽き果てる その時のウルトラマンの苦しむ姿にドキドキするって ヒーロー凌辱だぜ! 仮面かぶった拓也ゎ前見えねぇし 息ゎ苦しいし ウルトラマン最後の3分間ゎ30分以上にわたり 絶対負けるはずのないウルトラマンが倒れる そんなのあり得ない! 力尽きたウルトラマンが犯される マヂ苦しい 酸欠で死にそう

### ISSUE THREAD

**Issue by Minemu398** [sakura-tel/misskey-v11#8]

**Comment by Minemu398** [comment]
ウルトラマン拉致
ウルトラマンが拉致されて
腹筋ボコボコにパンチ食らって
胸のランプが点滅すると
あと3分で力尽き果てる
その時のウルトラマンの苦しむ姿にドキドキするって
ヒーロー凌辱だぜ!
仮面かぶった拓也ゎ前見えねぇし
息ゎ苦しいし
ウルトラマン最後の3分間ゎ30分以上にわたり
絶対負けるはずのないウルトラマンが倒れる
そんなのあり得ない!
力尽きたウルトラマンが犯される
マヂ苦しい
酸欠で死にそう
力が入らなくなったウルトラマンの股が大きく開かれて
ウルトラマンコにデカマラが容赦なく突き刺さる

脳天まで突き上げるファックに苦しみ喘ぐ息もマスクで塞がれて
最初ゎキュウキュウ締め付けていたウルトラマンコも
酸欠で意識が薄れてくると
最後ゎあの痙攣がやってくるウルトラマンだって死ぬときゎ射精するんだよ
「あー!!イク!! 」
ウルトラマンコにビクビクと弾丸が撃ち込まれると同時に
ウルトラマンも意識がぶっ飛び射精
そのあとピクピクと痙攣したまま動かなくなった

ウルトラマンの夢枕に現れたのゎ
あの、ターミネーター
「日本のウルトラマンは弱いな!!オレを見ろ!!絶対死なないぞ」
（あっ…あっ シュワちゃんだ）
「シュワッチ…シュワッチ!!」
「おいおい、気安く呼ぶなよ!!一応同盟国だから来てやったんだぜ!尖閣守ってやらねーぞ!!」
シュワちゃんから強力なバワーをもらって帰ると
ウルトラマンの星で家族会議が始まった
やっぱり
シュワッチゎ変えた方がいいかな

**Comment by remitocat** [comment]
reject
